---
- name: update web, nfs and db servers
  hosts: webservers, nfs, lb
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: delete wireshark on CentOS/RHEL
      yum:
        name: wireshark
        state: removed
      when: ansible_facts['os_family'] == 'RedHat'

- name: update LB server
  hosts: lb
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: delete wireshark on Ubuntu
      apt:
        name: wireshark-qt
        state: absent
        autoremove: yes
        purge: yes
        autoclean: yes

