[nfs]
172.31.26.91 ansible_ssh_user='ec2-user'

[webservers]
172.31.29.247 ansible_ssh_user='ec2-user'
172.31.20.250 ansible_ssh_user='ec2-user'

[db]
172.31.21.131 ansible_ssh_user='ec2-user' 

[lb]
172.31.20.15 ansible_ssh_user='ubuntu'