---
# tasks file for sonarqube
- name: set max_map
  become: true
  command: sysctl -w vm.max_map_count=262144

- name: set file max
  become: true
  command: sysctl -w fs.file-max=65536

 
- name: Add max limits
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    line: 
      - sonarqube   -   nofile   65536
      - sonarqube   -   nproc    4096
    create: yes


- name: Add ppa  repository 
  ansible.builtin.apt_repository:
    repo: 'deb http://ppa.launchpad.net/linuxuprising/java/ubuntu bionic main'

- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes

- name: install python3 and venv
  ansible.builtin.apt:
    name: 
      - python3
      - python3-venv
      - python3-dev
      - libpq-dev
    state: present

- name: Create a virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv /opt/sonar_venv

- name: Install setuptools in virtual environment
  ansible.builtin.command:
    cmd: /opt/sonar_venv/bin/pip install --upgrade setuptools

- name: Upgrade pip in virtual environment
  ansible.builtin.command:
    cmd: /opt/sonar_venv/bin/pip install --upgrade pip

- name: Install pip dependencies in virtual environment
  ansible.builtin.command:
    cmd: /opt/sonar_venv/bin/pip install psycopg2

- name: install java 11
  ansible.builtin.apt:
    name: 
      - openjdk-11-jdk
      - openjdk-11-jre
    state: present
    allow_unauthenticated: yes


- import_tasks: postgresql.yml

- name: Ensure group sonar exists
  ansible.builtin.group:
    name: sonar
    state: present

- import_tasks: sonarqube-setup.yml

- name: start and enable sonarqube
  ansible.builtin.service:
    name: sonar
    state: started
    enabled: yes