---

- name: Include dynamic variables
  hosts: all
  tasks:
    - include_vars: "../dynamic-assignments/env-vars.yml"
  tags:
    - always

- name: Webserver assignment
  hosts: webservers
  import_playbook: "../static-assignments/webservers.yml"

- name: Nginx assignment
  hosts: nginx
  import_playbook: "../static-assignments/nginx.yml"

- name: MySQL assignment
  hosts: mysql
  import_playbook: "../static-assignments/mysql.yml"
